# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Upload Image' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Upload Image
	pod 'Alamofire', '~> 4.7'
	pod 'RappleProgressHUD'
end
