# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def rx_swift
	pod 'RxSwift'
end

def rx_cocoa
	pod 'RxCocoa'
end

target 'Domain' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Domain
	rx_swift
end

target 'Mobile App' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mobile App
	rx_swift
	rx_cocoa
end
