# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def rx_swift
    pod 'RxSwift', '~> 4.3'
end

def rx_cocoa
    pod 'RxCocoa', '~> 4.3'
end

target 'Attedance Class' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Attedance Class
	rx_swift
	rx_cocoa
	pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git'
	pod 'ReachabilitySwift'
	pod 'IQKeyboardManagerSwift'
	pod 'JGProgressHUD'
	pod "KTSnackBar"
end

target 'Data' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Data
	pod 'SwiftyJSON', '~> 4.0'
	pod 'Alamofire', '~> 4.7'
	rx_swift
	rx_cocoa
	pod 'RxAlamofire'
end

target 'Device' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Device
	rx_swift
	rx_cocoa
	pod 'ReachabilitySwift'
end

target 'Domain' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Domain
	rx_swift
	rx_cocoa
end
